# Generated by Django 5.1.6 on 2025-03-02 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budgets.category'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='budgets/covers/%Y/%m/%d/'),
        ),
    ]
