# Generated by Django 5.1.6 on 2025-03-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_alter_budget_category_alter_budget_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
