# Generated by Django 5.1.6 on 2025-04-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_alter_budget_service_type_alter_budget_slug'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='tags',
            field=models.ManyToManyField(to='tag.tag'),
        ),
    ]
