# Generated by Django 5.1.6 on 2025-04-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_budget_tags'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='tags',
            field=models.ManyToManyField(blank=True, default='', to='tag.tag'),
        ),
    ]
