# Generated by Django 5.1.6 on 2025-04-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0006_alter_budget_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name': 'Budget', 'verbose_name_plural': 'Budgets'},
        ),
        migrations.AlterField(
            model_name='budget',
            name='title',
            field=models.CharField(max_length=65, verbose_name='Title'),
        ),
    ]
